Auth router
italomaia03/agendamento-consultas pull request #9
Opened 2024-04-25 20:42 UTC by dcbarros

2024-04-26 13:24 UTC, italomaia03 requested changes
Observar mudanças sugeridas

2024-04-26 13:24 UTC, italomaia03 commented on src/main/java/tech/ada/java/agendamentoconsultas/AgendamentoConsultasApplication.java
> +        final String apiTitle = "To-Do List API";
Trocar o título da API

2024-04-26 13:24 UTC, italomaia03 commented on src/main/java/tech/ada/java/agendamentoconsultas/controllers/AuthController.java
> +    // @PostMapping("/logout")
Adicionar rota de logout ou tirar código comentado

2024-04-26 13:24 UTC, italomaia03 commented on src/main/java/tech/ada/java/agendamentoconsultas/controllers/PatientController.java
> +    @PostMapping("/sign-in")
Rota de registro => /sign-up 

![image](https://github.com/italomaia03/agendamento-consultas/assets/109195782/6d4135bf-b644-41f1-8149-566b02bbbb85)

2024-04-26 17:02 UTC, dcbarros commented on src/main/java/tech/ada/java/agendamentoconsultas/controllers/AuthController.java
> +    // @PostMapping("/logout")
Ainda não tenho resposta para essa kkkkkkk

2024-04-26 17:04 UTC, dcbarros commented on src/main/java/tech/ada/java/agendamentoconsultas/controllers/PatientController.java
> +    @PostMapping("/sign-in")
já consertei isso kkkkk

2024-04-26 18:56 UTC, CaioLyra71 approved these changes

2024-04-28 17:28 UTC, italomaia03 approved these changes

2024-04-28 20:25 UTC, merged